# Generated by Django 5.1.3 on 2024-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=100)),
                ('file_upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
