# Generated by Django 5.1.3 on 2024-11-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signageApp', '0002_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='screen_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
