# Generated by Django 5.1.3 on 2024-11-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signageApp', '0005_asset_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
